import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'FOUNDER-0 Generated Product MVP',
  description: 'Autonomous MVP Application generated by FOUNDER-0',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  )
}
